import pygame 
pygame.init()
pygame.font.init()
# SYSTEM SETTINGS
WIDTH , HEIGHT = 800 , 800 
SYSTEM_BG_COLOR = (220,200,100) 
SYSTEM_BLANK = 75 

FONT_W , FONT_H = 20 , 20 
FONT_TYPE = "Corbell"



#  LEVEL EVENT SETTINGS 
LEVEL_EXIT = pygame.K_ESCAPE 

#  VISUALIZATON LEVEL SETTINGS 
SQUARE_COLOR = (128 , 0 , 128) 
SQUARE_WIDTH  , SQUARE_HEIGHT = 50 , 50 
SQUARE_BORDER = 2
BLANK_Y = (HEIGHT // 3) 
MATRIX_FONT_COLOR = (0,0,0)
BLANK_GRAPH = (WIDTH//3) 
CIRCLE_COLOR = (250,100,0) 

CORNER_BLANK = 50
LINKAGE_BORDER = 3









